---
- name: Installing service packages using dynamic loop
  hosts: redhat
  become: true
  vars_files: /root/ansible/vars_pkg.yml

  tasks: 
    - name: Install packages
      ansible.builtin.dnf:
         name: "{{ item.service }}"
         state: "{{ item.state }}"
      loop: "{{ packages }}"
