---
- name: Install & configure autofs service
  hosts: webservers
  become: true
  vars_files: 
    - /root/ansible/vars.yml  
  
  tasks: 
    - name: Install AutoFs service
      ansible.builtin.dnf:
        name: "{{ package_name }}"
        state: latest
