---
- name: Publish Web Content using Httpd
  hosts: node1
  become: true

  tasks: 
    - name: Installing Httpd package
      yum:
        name: httpd
        state: latest

    - name: Start & enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Adding web content
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart Apache Service # Triggers the handler if content changes

    - name: Allow http through the firewall
      firewalld:
        service: http
        immediate: yes # reload firewall
        permanent: true
        state: enabled

  handlers:          
    - name: Restart Apache Service # Runs only when notified by a task change
      service:
        name: httpd
        state: restarted

